version: '2'

#volumes: 
    #pulsevolume:
services:
        
    webaudioserver:
        build: ./docker-images/nodejs
        image: syntithenai/nodejs
        #depends_on: ['mongo']
        restart: always
        volumes:
          - "./snips-react-satellite:/usr/src/app/"
        #environment:
          #VIRTUAL_HOST: meeka.syntithenai.com
          #VIRTUAL_PORT: 7000
          #LETSENCRYPT_HOST: meeka.syntithenai.com
          #LETSENCRYPT_EMAIL: stever@syntithenai.com
          
        ports:
          - "3000:3000"
        
   
    ## ===========================================================================================   
    ## SNIPS ALL IN ONE
    ## ===========================================================================================   
    snips:
        depends_on: ['mosquitto']
        #privileged: true
        restart: always
        image: syntithenai/snips
        build: ./docker-images/snips
        #environment: ['PULSE_SERVER=unix:/tmp/pulse-socket','PULSE_COOKIE=unix:/tmp/pulse-cookie']
        environment: ['PULSE_SERVER=192.168.1.100','PULSE_COOKIE=/tmp/pulse-cookie']
        # export PULSE_COOKIE=/tmp/pulse-cookie; export PULSE_SERVER=192.168.1.100; pactl list
        volumes:
            - ./assistants/meekahome/assistant:/usr/share/snips/assistant
            #- /run/user/1000/pulse/native:/tmp/pulse-socket
            # in /etc/pulse/default.pa on the host maching 
            # CHANGE load-module module-native-protocol-unix  
            # TO  load-module module-native-protocol-unix  auth-anonymous=1 socket=/tmp/pulse-socket
            #- /tmp/pulse-socket:/tmp/pulse-socket
            - /home/stever/.config/pulse/cookie:/tmp/pulse-cookie
    
    # ===========================================================================================
    # SOUND SERVER  - FOR SHARED DEVICE ACCESS
    # ===========================================================================================
    #pulseaudio:
        #image: syntithenai/pulseaudio
        #build: ./docker-images/pulseaudio
        #privileged: true
        ## devices: ['/dev/snd']
        ## proxy for host pulseaudio server (my laptop)
        ##environment: ['PULSE_SERVER=192.168.1.100']
        ##pulseaudio
        #entrypoint: ['/usr/bin/pulseaudio']
        ##entrypoint: ['/bin/sleep','3600']
        #volumes: 
            ## pulseaudio access via shared socket
            #- pulsevolume:/tmp/pulse
            ## proxy for host pulseaudio server auth cookie
            #- /home/stever/.config/pulse/cookie:/home/snips/.pulse-cookie
            ##- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
                
    # ==========================================================================================
    # MQTT MESSAGING QUEUE -  WITH WEBSOCKETS
    # ===========================================================================================
    mosquitto:
        # see docker-images/manifest*.yml for multi arch config
        image: syntithenai/mosquitto
        restart: always
        ports:
            - 1883:1883
            # websockets enabled (for browser clients)
            - 9001:9001 
        volumes:
          # enable websockets
          - ./mosquitto-websockets.conf:/etc/mosquitto/conf.d/websockets.conf
          
     
